apiVersion: v1
kind: Secret
metadata:
  name: book-order-secrets
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  JWT_SECRET: demo-jwt-secret
  AUTH_DATABASE_URL: postgresql://postgres:postgres@auth-db:5432/auth_db
  BOOK_DATABASE_URL: postgresql://postgres:postgres@book-db:5432/book_db
  ORDER_DATABASE_URL: postgresql://postgres:postgres@order-db:5432/order_db
